export const portfolioWritups = [
  {
    id: 1,
    companyName: "Dentz Avenue",
    logo: "logo_8_dentz.svg",
    services: [
      "Consultancy",
      "Branding",
      "Content Creation",
      "Digital Marketing",
      "Web and App Development",
    ],
    location: "Colombo | Sri Lanka",
    timePeriod: "2022 December",
    product: "Rebranding",
    description: `We started working with Dentzz Avenue in marketing consultancy service and Dentz wanted to be a premium 
          dentistry. We began with research and business planning. Then we worked on the branding and visual identity
           as a premium brand. Adhering to the guidelines, we created content and published it through relevant 
           marketing channels, including revamping their website, which led to doubled sales within a year.`,
  },
  {
    id: 2,
    companyName: "Ceyestates",
    services: ["Content Creation"],
    location: "Colombo | Sri Lanka",
    timePeriod: "2022 January",
    product: "Company Profile",
    description:
      "Ceylon Estates is a locally manufactured tea company that exports to Europe. They wanted a short, non-verbal company profile. We created a visual story showing their stakeholders, the tea origins, labor appreciation, product quality, and the production process from plucking tea leaves to brewing a teacup.",
  },
  {
    id: 3,
    companyName: "Lion Brewery",
    logo: "logo_6_lion.svg",
    services: ["Consultancy", "Branding", "Content Creation"],
    location: "Colombo | Sri Lanka",
    timePeriod: "2023 July",
    product: "Mobile Bar",
    description:
      "Lion Brewery wanted a mobile beer vessel. We crafted a strategy for a portable beer vessel that complied with government regulations. We proposed partnering with Barnhouse, branding it as 'The Bar’n Truck'. We maintained Lion’s 'Adventure' theme by using a yellow Defender to tow the truck, giving a Camel Trophy vibe while reinforcing Lion Brewery’s adventure branding. The tagline was 'Cheers to your next adventure.'",
  },
  {
    id: 4,
    companyName: "Carlsberg",
    logo: "logo_4_carsburg.svg",
    services: ["Consultancy", "Web and App Development"],
    location: "Colombo | Sri Lanka",
    timePeriod: "2024 June",
    product: "Trivia Game App",
    description:
      "To increase customer engagement, we developed a trivia game app for Carlsberg. The app, aimed at beer consumers, promotes brand awareness and provides entertainment when customers visit restaurants.",
  },
  {
    id: 5,
    companyName: "Moon River",
    logo: "logo_9_moon_river.svg",
    services: ["Consultancy", "Content Creation", "Digital Marketing"],
    location: "Colombo | Sri Lanka",
    timePeriod: "2023 December",
    product: "Digital Marketing Campaign",
    description:
      "Moon River wanted to boost its digital presence. We crafted high-quality content and published it on trending social media platforms to attract organic audiences. This strategy helped Moon River, an old restaurant, gain a youthful target audience.",
  },
  {
    id: 6,
    companyName: "GSS Labs",
    services: ["Content Creation"],
    location: "USA",
    timePeriod: "2023 May",
    product: "Video Production",
    description:
      "GSS Labs needed a video advertisement with a Sri Lankan bodybuilding champion for their product launch in Asia. We produced a video for their global market launch.",
  },
  {
    id: 7,
    companyName: "Emporium",
    services: [
      "Consultancy",
      "Branding",
      "Content Creation",
      "Digital Marketing",
    ],
    location: "Kandy | Sri Lanka",
    timePeriod: "2022 June",
    product: "Rebranding",
    description:
      "Kandurata Emporium rebranded as 'Emporium' for global expansion. Our research found that people associated 'emporium' with royalty, so we designed the brand with a regal theme. We drew inspiration from the last Kandyan king's crown, which featured four unique gems. This rebranding created a premium, export-quality brand with a royal aesthetic, leading to strong sales and a successful global launch.",
  },
  {
    id: 8,
    companyName: "Jimith Sirinandana",
    services: ["Consultancy", "Branding", "Content Creation"],
    location: "Melbourne | Australia",
    timePeriod: "2021 December",
    product: "Personal Branding",
    description:
      "Jimith, an upcoming drummer, sought marketing support to enhance his personal brand as an artist, teacher, and drum influencer. We developed his personal branding strategy, executed a photoshoot, and created social media guidelines. Jimith is now an endorsed drummer with Paiste Cymbals, based in Australia.",
  },
  {
    id: 9,
    companyName: "VIP Party and Events",
    services: ["Web and App Development"],
    location: "Colombo | Sri Lanka",
    timePeriod: "2021 December",
    product: "Web Development",
    description:
      "VIP Party and Events, an event management company in Sri Lanka specializing in 360 cameras and photobooths, tasked us with designing and developing their website. The site was nominated for the Best Web Awards Sri Lanka.",
  },
  {
    id: 10,
    companyName: "Guinness Beer",
    services: ["Content Creation"],
    location: "Colombo | Sri Lanka",
    timePeriod: "2022 March",
    product: "Product Photography",
    description:
      "We handled the photoshoot for Guinness Beer during its launch in Sri Lanka.",
  },
  {
    id: 11,
    companyName: "SLIA",
    services: ["Digital Marketing"],
    location: "Colombo | Sri Lanka",
    timePeriod: "",
    product: "Exhibition Promotion",
    description: "",
  },
  {
    id: 12,
    companyName: "Khaleed House Hotel Chain",
    services: ["Content Creation"],
    location: "",
    timePeriod: "",
    product: "Photoshoot",
    description: "",
  },
  {
    id: 13,
    companyName: "HOT Photos and Videos",
    services: ["Content Creation"],
    location: "",
    timePeriod: "",
    product: "",
    description: "",
  },
  {
    id: 14,
    companyName: "Avenue with Brand Kit",
    services: ["Consultancy", "Branding", "Digital Marketing"],
    location: "",
    timePeriod: "",
    product: "",
    description: "",
  },
  {
    id: 15,
    companyName: "Ceylon Tropical Escapes",
    logo: "logo_10_ceylon_tropical.svg",
    services: ["Consultancy", "Branding"],
    location: "",
    timePeriod: "",
    product: "",
    description: "",
  },
  {
    id: 16,
    companyName: "Colombo Percussion",
    services: ["Branding"],
    location: "",
    timePeriod: "",
    product: "",
    description: "",
  },
  {
    id: 17,
    logo: "logo_5_advatis.svg",
    companyName: "Advantis",
    services: ["Digital Marketing"],
    location: "",
    timePeriod: "",
    product: "",
    description: "",
  },
  {
    id: 18,
    companyName: "MSI",
    services: ["Consultancy", "Web and App Development"],
    location: "",
    timePeriod: "",
    product: "",
    description: "",
  },
];
